// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Samsung s25 Galaxy",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Samsung S25",
                            Price = 98000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Samsung s24 Galaxy",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Samsung S24",
                            Price = 80000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Description = "Samsung s23 Galaxy",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Samsung S23",
                            Price = 70000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Samsung s22 Galaxy",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Samsung S22",
                            Price = 60000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "Samsung s21 Galaxy",
                            ImageUrl = "https://via.placeholder.com/150",
                            IsActive = true,
                            Name = "Samsung S21",
                            Price = 50000m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
